-- MySQL Script generated by MySQL Workbench
-- Sat Oct 14 23:51:43 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ocorrencia_online_laravel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ocorrencia_online_laravel` ;

-- -----------------------------------------------------
-- Schema ocorrencia_online_laravel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ocorrencia_online_laravel` DEFAULT CHARACTER SET latin1 ;
USE `ocorrencia_online_laravel` ;

-- -----------------------------------------------------
-- Table `ocorrencia_online_laravel`.`policial_civil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencia_online_laravel`.`policial_civil` ;

CREATE TABLE IF NOT EXISTS `ocorrencia_online_laravel`.`policial_civil` (
  `POLICIAL_CIVIL_MATRICULA` INT(11) NOT NULL AUTO_INCREMENT,
  `POLICIAL_CIVIL_NOME` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`POLICIAL_CIVIL_MATRICULA`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ocorrencia_online_laravel`.`municipios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencia_online_laravel`.`municipios` ;

CREATE TABLE IF NOT EXISTS `ocorrencia_online_laravel`.`municipios` (
  `MUNICIPIO_COD` INT(11) NOT NULL AUTO_INCREMENT,
  `MUNICIPIO_NOME` VARCHAR(255) NOT NULL,
  `MUNICIPIO_GV` TINYINT NOT NULL,
  `MUNICIPIO_UF` CHAR(2) NOT NULL,
  PRIMARY KEY (`MUNICIPIO_COD`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ocorrencia_online_laravel`.`tp_logradouro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencia_online_laravel`.`tp_logradouro` ;

CREATE TABLE IF NOT EXISTS `ocorrencia_online_laravel`.`tp_logradouro` (
  `TP_LOGRADOURO_COD` INT(11) NOT NULL AUTO_INCREMENT,
  `TP_LOGRADOURO_NOME` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`TP_LOGRADOURO_COD`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ocorrencia_online_laravel`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencia_online_laravel`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `ocorrencia_online_laravel`.`usuarios` (
  `USUARIO_COD` INT(11) NOT NULL AUTO_INCREMENT,
  `USUARIO_NOME` VARCHAR(70) NOT NULL,
  `USUARIO_DT_NASCI` DATE NOT NULL,
  `USUARIO_IDENTIDADE` INT(11) NOT NULL,
  `USUARIO_CPF` BIGINT(11) NOT NULL,
  `USUARIO_NOME_MAE` VARCHAR(70) NOT NULL,
  `USUARIO_TEL_CEL` BIGINT(11) NOT NULL,
  `USUARIO_EMAIL` VARCHAR(255) NOT NULL,
  `USUARIO_FOTO_ROSTO` VARCHAR(20) NOT NULL,
  `USUARIO_FOTO_DOC` VARCHAR(20) NOT NULL,
  `MUNICIPIO_COD` INT(11) NOT NULL,
  `TP_LOGRADOURO_COD` INT(11) NOT NULL,
  `USUARIO_LOGRADOURO` VARCHAR(255) NOT NULL,
  `USUARIO_NUMERO_RES` SMALLINT(10) NOT NULL,
  `USUARIO_COMPLEMENTO_RES` VARCHAR(255) NULL DEFAULT NULL,
  `USUARIO_BAIRRO` VARCHAR(255) NOT NULL,
  `USUARIO_CEP` INT(9) NOT NULL,
  `USUARIO_SENHA` VARCHAR(64) NOT NULL,
  `USUARIO_DT_REGISTRO` DATETIME NOT NULL,
  `POLICIAL_CIVIL_MATRICULA` INT(11) NULL DEFAULT NULL,
  `USUARIO_DT_APROVADO` DATETIME NULL DEFAULT NULL,
  `USUARIO_AP_SIC` TINYINT NULL DEFAULT 0,
  `USUARIO_AP_OPERADORA` TINYINT NULL DEFAULT 0,
  `USUARIO_AP_FOTOS` TINYINT NULL DEFAULT 0,
  `remember_token` VARCHAR(100) NULL,
  `USUARIO_IP_REGISTRO` VARCHAR(15) NULL,
  PRIMARY KEY (`USUARIO_COD`),
  INDEX `MUNICIPIO_COD` (`MUNICIPIO_COD` ASC),
  INDEX `TP_LOGRADOURO_COD` (`TP_LOGRADOURO_COD` ASC),
  INDEX `POLICIAL_CIVIL_MATRICULA` (`POLICIAL_CIVIL_MATRICULA` ASC),
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`MUNICIPIO_COD`)
    REFERENCES `ocorrencia_online_laravel`.`municipios` (`MUNICIPIO_COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuarios_ibfk_2`
    FOREIGN KEY (`TP_LOGRADOURO_COD`)
    REFERENCES `ocorrencia_online_laravel`.`tp_logradouro` (`TP_LOGRADOURO_COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuarios_ibfk_3`
    FOREIGN KEY (`POLICIAL_CIVIL_MATRICULA`)
    REFERENCES `ocorrencia_online_laravel`.`policial_civil` (`POLICIAL_CIVIL_MATRICULA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ocorrencia_online_laravel`.`tp_ocorrencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencia_online_laravel`.`tp_ocorrencia` ;

CREATE TABLE IF NOT EXISTS `ocorrencia_online_laravel`.`tp_ocorrencia` (
  `TP_OCORRENCIA_COD` INT(11) NOT NULL AUTO_INCREMENT,
  `TP_OCORRENCIA_NOME` VARCHAR(128) NOT NULL,
  `TP_OCORRENCIA_DESC` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`TP_OCORRENCIA_COD`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ocorrencia_online_laravel`.`ocorrencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencia_online_laravel`.`ocorrencias` ;

CREATE TABLE IF NOT EXISTS `ocorrencia_online_laravel`.`ocorrencias` (
  `OCORRENCIA_COD` INT(11) NOT NULL AUTO_INCREMENT,
  `USUARIO_COD` INT(11) NOT NULL,
  `TP_OCORRENCIA_COD` INT(11) NOT NULL,
  `OCORRENCIA_DATA` DATE NOT NULL,
  `OCORRENCIA_DESC` LONGTEXT NOT NULL,
  `MUNICIPIO_COD` INT(11) NOT NULL,
  `TP_LOGRADOURO_COD` INT(11) NULL,
  `OCORRENCIA_LOGRADOURO` VARCHAR(255) NULL,
  `OCORRENCIA_NUM_LOCAL` CHAR(10) NULL,
  `OCORRENCIA_COMPLEMENTO_LOCAL` VARCHAR(255) NULL DEFAULT NULL,
  `OCORRENCIA_BAIRRO` VARCHAR(255) NULL,
  `OCORRENCIA_CEP` INT(11) NULL,
  `OCORRENCIA_LAT` DECIMAL(10,8) NULL,
  `OCORRENCIA_LONG` DECIMAL(11,8) NULL,
  `OCORRENCIA_IP_REG` VARCHAR(15) NULL,
  PRIMARY KEY (`OCORRENCIA_COD`),
  INDEX `MUNICIPIO_COD` (`MUNICIPIO_COD` ASC),
  INDEX `USUARIO_COD` (`USUARIO_COD` ASC),
  INDEX `TP_LOGRADOURO_COD` (`TP_LOGRADOURO_COD` ASC),
  INDEX `TP_OCORRENCIA_COD` (`TP_OCORRENCIA_COD` ASC),
  CONSTRAINT `ocorrencias_ibfk_1`
    FOREIGN KEY (`MUNICIPIO_COD`)
    REFERENCES `ocorrencia_online_laravel`.`municipios` (`MUNICIPIO_COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ocorrencias_ibfk_2`
    FOREIGN KEY (`USUARIO_COD`)
    REFERENCES `ocorrencia_online_laravel`.`usuarios` (`USUARIO_COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ocorrencias_ibfk_3`
    FOREIGN KEY (`TP_LOGRADOURO_COD`)
    REFERENCES `ocorrencia_online_laravel`.`tp_logradouro` (`TP_LOGRADOURO_COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ocorrencias_ibfk_4`
    FOREIGN KEY (`TP_OCORRENCIA_COD`)
    REFERENCES `ocorrencia_online_laravel`.`tp_ocorrencia` (`TP_OCORRENCIA_COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ocorrencia_online_laravel`.`atendimentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencia_online_laravel`.`atendimentos` ;

CREATE TABLE IF NOT EXISTS `ocorrencia_online_laravel`.`atendimentos` (
  `ATENDIMENTO_COD` INT(11) NOT NULL AUTO_INCREMENT,
  `OCORRENCIA_COD` INT(11) NOT NULL,
  `POLICIAL_CIVIL_MATRICULA` INT(11) NOT NULL,
  `ATENDIMENTO_DATA` DATETIME NOT NULL,
  `ATENDIMENTO_DESC` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`ATENDIMENTO_COD`),
  INDEX `POLICIAL_CIVIL_MATRICULA` (`POLICIAL_CIVIL_MATRICULA` ASC),
  INDEX `OCORENCIA_COD` (`OCORRENCIA_COD` ASC),
  CONSTRAINT `atendimentos_ibfk_1`
    FOREIGN KEY (`POLICIAL_CIVIL_MATRICULA`)
    REFERENCES `ocorrencia_online_laravel`.`policial_civil` (`POLICIAL_CIVIL_MATRICULA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `atendimentos_ibfk_2`
    FOREIGN KEY (`OCORRENCIA_COD`)
    REFERENCES `ocorrencia_online_laravel`.`ocorrencias` (`OCORRENCIA_COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ocorrencia_online_laravel`.`tp_envolvimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencia_online_laravel`.`tp_envolvimento` ;

CREATE TABLE IF NOT EXISTS `ocorrencia_online_laravel`.`tp_envolvimento` (
  `TP_ENVOLVIMENTO_COD` INT(11) NOT NULL AUTO_INCREMENT,
  `TP_ENVOLVIMENTO_NOME` VARCHAR(128) NOT NULL,
  `TP_ENVOLVIMENTO_DESC` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`TP_ENVOLVIMENTO_COD`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ocorrencia_online_laravel`.`envolvidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencia_online_laravel`.`envolvidos` ;

CREATE TABLE IF NOT EXISTS `ocorrencia_online_laravel`.`envolvidos` (
  `ENVOLVIDO_COD` INT(11) NOT NULL AUTO_INCREMENT,
  `OCORRENCIA_COD` INT(11) NOT NULL,
  `ENVOLVIDO_NOME` VARCHAR(70) NOT NULL,
  `ENVOLVIDO_IDENTIDADE` INT(11) NOT NULL,
  `ENVOLVIDO_CPF` BIGINT(11) NULL,
  `ENVOLVIDO_DT_NASC` DATE NULL DEFAULT NULL,
  `ENVOLVIDO_NOME_MAE` VARCHAR(70) NULL DEFAULT NULL,
  `ENVOLVIDO_TEL_CONTATO` BIGINT(11) NULL,
  `TP_ENVOLVIMENTO_COD` INT(11) NOT NULL,
  `MUNICIPIO_COD` INT(11) NOT NULL,
  `TP_LOGRADOURO_COD` INT(11) NULL,
  `ENVOLVIDO_LOGRADOURO` VARCHAR(255) NULL DEFAULT NULL,
  `ENVOLVIDO_NUM_RES` CHAR(10) NULL DEFAULT NULL,
  `ENVOLVIDO_COMP_RES` VARCHAR(255) NULL DEFAULT NULL,
  `ENVOLVIDO_BAIRRO` VARCHAR(255) NULL,
  `ENVOLVIDO_CEP` INT(9) NULL DEFAULT NULL,
  PRIMARY KEY (`ENVOLVIDO_COD`),
  INDEX `MUNICIPIO_COD` (`MUNICIPIO_COD` ASC),
  INDEX `OCORENCIA_COD` (`OCORRENCIA_COD` ASC),
  INDEX `TP_ENVOLVIMENTO_COD` (`TP_ENVOLVIMENTO_COD` ASC),
  INDEX `TP_LOGRADOURO_COD` (`TP_LOGRADOURO_COD` ASC),
  CONSTRAINT `envolvidos_ibfk_1`
    FOREIGN KEY (`MUNICIPIO_COD`)
    REFERENCES `ocorrencia_online_laravel`.`municipios` (`MUNICIPIO_COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `envolvidos_ibfk_2`
    FOREIGN KEY (`OCORRENCIA_COD`)
    REFERENCES `ocorrencia_online_laravel`.`ocorrencias` (`OCORRENCIA_COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `envolvidos_ibfk_3`
    FOREIGN KEY (`TP_ENVOLVIMENTO_COD`)
    REFERENCES `ocorrencia_online_laravel`.`tp_envolvimento` (`TP_ENVOLVIMENTO_COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `envolvidos_ibfk_4`
    FOREIGN KEY (`TP_LOGRADOURO_COD`)
    REFERENCES `ocorrencia_online_laravel`.`tp_logradouro` (`TP_LOGRADOURO_COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ocorrencia_online_laravel`.`un_medida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencia_online_laravel`.`un_medida` ;

CREATE TABLE IF NOT EXISTS `ocorrencia_online_laravel`.`un_medida` (
  `UN_MEDIDA_COD` INT(11) NOT NULL AUTO_INCREMENT,
  `UN_MEDIDA_NOME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`UN_MEDIDA_COD`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ocorrencia_online_laravel`.`tp_objeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencia_online_laravel`.`tp_objeto` ;

CREATE TABLE IF NOT EXISTS `ocorrencia_online_laravel`.`tp_objeto` (
  `TP_OBJETO_COD` INT(11) NOT NULL AUTO_INCREMENT,
  `TP_OBJETO_NOME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`TP_OBJETO_COD`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ocorrencia_online_laravel`.`objetos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencia_online_laravel`.`objetos` ;

CREATE TABLE IF NOT EXISTS `ocorrencia_online_laravel`.`objetos` (
  `OBJETO_COD` INT(11) NOT NULL AUTO_INCREMENT,
  `OCORRENCIA_COD` INT(11) NOT NULL,
  `TP_OBJETO_COD` INT(11) NOT NULL,
  `UN_MEDIDA_COD` INT(11) NOT NULL,
  `OBJETO_QUANT` CHAR(10) NULL,
  `OBJETO_DESC` MEDIUMTEXT NULL,
  PRIMARY KEY (`OBJETO_COD`),
  INDEX `OCORENCIA_COD` (`OCORRENCIA_COD` ASC),
  INDEX `UN_MEDIDA_COD` (`UN_MEDIDA_COD` ASC),
  INDEX `TP_OBJETO_COD` (`TP_OBJETO_COD` ASC),
  CONSTRAINT `objetos_ibfk_1`
    FOREIGN KEY (`OCORRENCIA_COD`)
    REFERENCES `ocorrencia_online_laravel`.`ocorrencias` (`OCORRENCIA_COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `objetos_ibfk_2`
    FOREIGN KEY (`UN_MEDIDA_COD`)
    REFERENCES `ocorrencia_online_laravel`.`un_medida` (`UN_MEDIDA_COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `objetos_ibfk_3`
    FOREIGN KEY (`TP_OBJETO_COD`)
    REFERENCES `ocorrencia_online_laravel`.`tp_objeto` (`TP_OBJETO_COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
